### ISSUE TITLE
Highlight Selected Menu Item

### ISSUE THREAD

**Issue by yalematta** [yalematta/yalematta.github.io#2]
Underline or make menu items bold when selected.

**Comment by Umesh-01** [comment]
can u tell me where is this menu content available??

**Comment by yalematta** [comment]
> can u tell me where is this menu content available??

It's the ` <nav class="menu-content">` inside _menu.html_ under the `includes` folder

**Comment by Umesh-01** [comment]
and css file for this, is `main.css` in `css` inside `assets` folder !!
am I right??

**Comment by Umesh-01** [comment]
I have done...
@yalematta

**Comment by yalematta** [comment]
> I have done...

Thank you @Umesh-01 for taking the time to submit a pull request. 

But as mentioned we would like to have the menu _underlined_ or _in bold_ **while we are opening its corresponding page** 
and not only when we hover over the menu title. 

If you have the time to look into it that would be awesome, otherwise thanks for you've done 🙏

**Comment by Umesh-01** [comment]
@yalematta yes I know, it was LGTM

**Comment by Umesh-01** [comment]
but ur website was using only two colors i.e. strong blue (#0070C9) and  payne's grey (#48484A), so I thought it will match the other colors 👍 if it will be blue on hovering over the menu items.   As per ur choice it will look different than other elements, think about it... @yalematta 

Otherwise, just leave a comment here if u want me to change it....
I will do it according to ur choice... 🙂

**Comment by yalematta** [comment]
We just need it to stay **underlined** once it is clicked and until we click another menu item / move to another page.

**Comment by Umesh-01** [comment]
What about that blue color highlight, should I leave it as it is, for this issue "**underlined** once it is clicked" I will try. 
but I need some time...

**Comment by Umesh-01** [comment]
I tried @yalematta , but didn't make it... 🙁 

I think it's due to this code inside `_includes` in `menu.html` file

``` css
<nav class="menu-content">
    {% for item in site.data.settings.menu %}
      <a href="{{ site.github.url }}/{{ item.path }}/{{ item.url }}">{{ item.name }}</a>
    {% endfor %}
</nav>
```

Because this code is calling all the menu items through a single line and if I am applying any class to this then it's changing the style (underline/bold/color) of all the menu items...

And according to me, to make this possible someone have to change this code inside `_data` in `settings.yml` file

```css
menu: 
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Talking', path: 'menu', url: 'talking.html'}
```

I am not an expert, so I don't want to mess up with something which is out of my knowledge...
Thank u 🙂

**Comment by Naufal2511** [comment]
Can I work on this and give it a try. I understood the task
